<h2>Terms of service</h2>
<p>Please just don't be a dick when using this service. What is considered being a dick is up to the hosters of this website. Often being a dick can be prevented by applying some common sense and not breaking stuff.</p>
<h3>Liability</h3>
<p>We are not responsible / liable for whatever content you find, download, copy, upload on this website. If you want to sue us please see the first paragraph of this document (the part about not being a dick).</p>