<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php if (isset($this->templateVariables['download'])) { ?>
    <META http-equiv="refresh" content="0;URL=/download-file/<?php echo $this->templateVariables['download']; ?>">
    <?php } ?>
    <link href='http://fonts.googleapis.com/css?family=Oleo+Script:700' rel='stylesheet' type='text/css'>
    <link href="/style/style.css" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-iphone.png">
    <script>
      if (window!=top){top.location.href=location.href;}
      document.createElement('header');
      document.createElement('nav');
      document.createElement('section');
      document.createElement('article');
      document.createElement('aside');
      document.createElement('footer');
      document.createElement('time');
    </script>
  </head>
  <body>
    <header>
      <div id="header">
        <h1>File<span>Upload</span></h1>
        <?php
        if ($this->templateVariables['isUserLoggedIn']) {
            echo $this->renderTemplate('header/logged-in.phtml');
        } else {
            echo $this->renderTemplate('header/not-logged-in.phtml');
        }
        ?>
      </header>
    </header>
    <div id="body">
      <?php echo $this->templateVariables['pageContent']; ?>
      <footer>
        <ul>
          <li><a href="#">About</a></li>
          <li><a href="#">Terms of service</a></li>
          <li>Copyright © 2012 <a href="http://www.pieterhordijk.com" target="_blank">Pieter Hordijk</a></li>
        </ul>
      </footer>
    </div>
    <script src="/js/XMLHttpRequest.js"></script>
    <script src="/js/qqfileuploader.js"></script>
    <script src="/js/DomHandler.js"></script>
    <script src="/js/Array.js"></script>
    <script src="/js/Popup.js"></script>
    <script src="/js/Authentication.js"></script>
    <script src="/js/FixHeight.js"></script>
    <script src="/js/FilesOverview.js"></script>
    <script src="/js/Menu.js"></script>
    <script src="/js/Page.js"></script>
    <script src="/js/FileUploader.js"></script>
    <script src="/js/site.js"></script>
</body>
</html>