<h2 class="download">Password protected</h2>
<p class="download">This resource is password protected. Please enter the password.</p>
<div class="popup" style="display: none;">
  <form action="/download/password/<?php echo $this->templateVariables['file']['uploadid']; ?>" method="post" class="password">
    <input type="hidden" name="csrf-token" value="LODN3TgqdSx9EFcvC5qq2EZwfW6g7FtVlN0YwPhpUAynxDCKD1DAGIEqbuwniQxHuoBW965XCirVMkM7b1Fd9xkeqLoYOmG3mRBH5XVHbgjHORPuuhrdk3SvInWEg">
    <p>This resource is password protected. Please enter the password.</p>
    <input type="password" name="password" placeholder="Password">
    <input type="submit" name="submit" value="Download" class="btn">
  </form>
</div>