<table class="file-list">
  <tr>
    <th class="filename">Original filename</th>
    <th class="name">Name</th>
    <th class="description">Description</th>
    <th class="access">Access</th>
    <th class="timestamp">Timestamp</th>
    <th class="downloads">Downloads</th>
    <th class="edit">&nbsp;</th>
    <th class="delete">&nbsp;</th>
  </tr>
  <?php foreach ($this->templateVariables['files'] as $file) { ?>
    <tr>
      <td class="filename"><?php echo basename(htmlspecialchars(urldecode($file['filename']))); ?></td>
      <td class="name"><?php echo htmlspecialchars($file['name'], ENT_QUOTES, 'UTF-8'); ?></td>
      <td class="description"><?php echo htmlspecialchars($file['description'], ENT_QUOTES, 'UTF-8'); ?></td>
      <td class="access">Private</td>
      <td class="timestamp"><?php echo (new DateTime($file['timestamp']))->format('d-m-Y'); ?></td>
      <td class="downloads">9999999</td>
      <td class="edit"><a href="/your-files/<?php echo $file['uploadid']; ?>/edit">Edit</a></td>
      <td class="delete"><a href="/your-files/<?php echo $file['uploadid']; ?>/delete/<?php echo $this->templateVariables['csrfToken']; ?>">Delete</a></td>
    </tr>
  <?php } ?>
</table>