<table class="file-list">
  <tr>
    <th class="original-filename">Original filename</th>
    <th class="tags">Tags</th>
    <th class="access">Access</th>
    <th class="timestamp">Timestamp</th>
    <th class="downloads">Downloads</th>
    <th class="edit">&nbsp;</th>
    <th class="delete">&nbsp;</th>
  </tr>
  <?php foreach ($this->templateVariables['files'] as $file) { ?>
    <tr>
      <td class="original-filename"><?php echo $file['filename']; ?></td>
      <td class="tags">
        <?php if ($file['tags']) foreach ($file['tags'] as $tag) { ?>
          <a href="#"><?php echo $tag; ?></a>
        <?php } ?>
      </td>
      <td class="access">Private</td>
      <td class="timestamp"><?php echo (new DateTime($file['timestamp']))->format('d-m-Y'); ?></td>
      <td class="downloads">9999999</td>
      <td class="edit"><a href="#">Edit</a></td>
      <td class="delete"><a href="#">Delete</a></td>
    </tr>
  <?php } ?>
</table>